include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - engine/target/
    - examples-plain/target/
    - examples-spring-boot/target/
    - spring-boot-starter-flusswerk/target/
    - integration-test/target/