# Default spring profile is local
---
spring:
  application:
    name: flusswerk-example
  profiles:
    active: local
  jmx:
    enabled: true

flusswerk:
  processing:
    threads: 5
  routing:
    incoming:
      - incoming
    outgoing:
      default: next
    failure policies:
      incoming:
        maxRetries: 5

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include:
          - prometheus
          - metrics
          - info
          - health
  info:
    git:
      mode: full

server:
  port: 12345

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: DEV
flusswerk:
  rabbitmq:
    hosts:
      - rabbitmq.dev
    username: secret
    password: secret

---
spring:
  config:
    activate:
      on-profile: STG
flusswerk:
  rabbitmq:
    hosts:
      - rabbitmq.stg
    username: secret
    password: secret

---
spring:
  config:
    activate:
      on-profile: PROD
flusswerk:
  rabbitmq:
    hosts:
      - rabbitmq.prod
    username: secret
    password: secret
