---
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [25]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          check-latest: true
          distribution: temurin
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-maven-artifacts
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Get main for spotless
        run: git fetch origin main
      - name: Build with Maven
        run: mvn -B verify
